# Cloudflare Pages configuration
[build]
command = "npm run build"
node_compat = true
node_version = "18.18.0"

[site]
bucket = ".next"

# Add this for Cloudflare Pages configuration
[pages]
compatibility_date = "2024-06-15"
compatibility_flags = ["nodejs_compat"]

# Define the output directory for the built assets
[pages.build]
command = "npm run build"
output_directory = ".vercel/output/static" 