# Cloudflare Pages configuration
name = "gannet-website"
pages_build_output_dir = "out"  # For Next.js static export
compatibility_date = "2024-06-15"
compatibility_flags = ["nodejs_compat"]
build.command = "npm run build" 