# Cloudflare Pages configuration
name = "gannet-website"
compatibility_date = "2024-06-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# Define the output directory for the built assets
pages_build_output_dir = "out" 