# Simplified Cloudflare Pages configuration
name = "gannet-website"

[build]
command = "npm run cloudflare:build"

[build.environment]
NODE_VERSION = "18.18.0"
NPM_FLAGS = "--no-audit --no-fund"

[site]
bucket = ".vercel/output/static" 